name: Deployment to Heroku 

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "unimelb-course-planner" #Must be unique in Heroku
          heroku_email: "jinchenr@student.unimelb.edu.au"
